### ISSUE TITLE
Some required patches don't get applied

### ISSUE THREAD

**Issue by toomuchdesign** [musement/types-generator#5]
I'm using this library against `https://api.musement.com/swagger_3.4.0.json` and heavily relying on `--patchSource` option to patch the original swagger definition and manually set the required props.

I found out that a few entities don't receive the required attributes specified in the patch file:

Patch file
```
"CartItemMusementGiftbox": {
  "required": ["type", "product"]
},
```

Output
``` ts
export type CartItemMusementGiftbox = CartItem & {
  type?: "musement-giftbox",
  product?: Giftbox
} & {};
```
It seems to happen with types declared as union of other types.
I noticed that the declaration shows and extra `& {}` appended at the and of it. Could it be that the patch gets applied to this empty object type?

**Comment by zi** [comment]
The problem is that the schema you have after applying the patch is this:
```json
{
  "CartItemMusementGiftbox": {
    "type": "object",
    "allOf": [
      {
        "$ref": "#/components/schemas/CartItem"
      },
      {
        "properties": {
          "type": {
            "type": "string",
            "enum": ["musement-giftbox"]
          },
          "product": {
            "$ref": "#/components/schemas/Giftbox"
          }
        },
        "type": "object"
      }
    ],
    "required": ["type", "product"]
  }
}
```

I'm not sure this is a valid OpenApi format,

You could overwrite the whole `CartItemMusementGiftbox` model like this:
```json
{
  "CartItemMusementGiftbox": {
    "allOf": [
      {
        "$ref": "#/components/schemas/CartItem"
      },
      {
        "properties": {
          "type": {
            "type": "string",
            "enum": ["musement-giftbox"]
          },
          "product": {
            "$ref": "#/components/schemas/Giftbox"
          }
        },
        "type": "object",
        "required": ["type", "product"]
      }
    ]
  }
}

```

**Comment by toomuchdesign** [comment]
Yep, that was definitely the issue!
I didn't realize the patch was actually meant to be merged with the original schema. 👍 

Thanks so much 🙌
